framework:
    workflows:
        validate_article:
            type: 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                type: method
                property: 'state'
            supports:
                - App\Entity\Article
            places:
                - review
                - publish
            initial_marking: review
            transitions:
                published:
                    guard: "is_fully_authenticated()"
                    from: review
                    to: publish
                unpublished:
                    guard: "is_fully_authenticated()"
                    from: publish
                    to: review
